---
- name: Run user tasks
  ansible.builtin.include_tasks: users.yml
  when: system_users_enabled
  tags:
    - users

- name: Run ssh tasks
  ansible.builtin.include_tasks: ssh.yml
  when: system_ssh_enabled
  tags:
    - ssh

- name: Run unattended-upgrades tasks
  ansible.builtin.include_tasks: unattended-upgrades.yml
  when: system_unattended_upgrades_enabled
  tags:
    - unattended-upgrades
